### PR TITLE
add herbgarden

### PR DESCRIPTION
**Pull request by Cl0ckm4n**

### CODE REVIEW

**Comment by MasterZydra** [comment]
Thanks @Cl0ckm4n. I will take a look tomorrow

**Comment by MasterZydra** [comment]
Hi @Cl0ckm4n,
I tested the "getDailyBoni" function.
"bonus.collectBonusitemPoints" is failing.

**Comment by Cl0ckm4n** [comment]
Ouh... maybe its because a premium account is required for this feature...

Didn't think of that. So we need a check if a premium account is active?!

**Comment by MasterZydra** [comment]
That could be possible. I do not have an premium account. And I do not have a option to collect all bonus items at once.

**Comment by Cl0ckm4n** [comment]
Ok i will look into it and push an update the next days... :)

**Comment by Cl0ckm4n** [comment]
i added some queries for an active premium account and a guild membership. i tested it and i think it should work now, please have a look :D

**Comment by MasterZydra** [comment]
Thanks. I will try to take a look on the weekend

**Comment by MasterZydra** [comment]
Hi @Cl0ckm4n,
Because of the conflicts it was not possible to use this PR directly.
But I copied all changes and marked you as coauthor (see 50e5337d14da39959841b93dbef0ddd15e000d69).

Thanks for the changes :+1:

**Comment by Cl0ckm4n** [comment]
Thanks. And sorry for the inconvenience, this was coded way before the code change...

**Pull request closed without merging**
