### PR TITLE
Fixes bonsai

### LINKED ISSUE #55: automate bonsaigarden
I wanted to automate the branch cutting and replacing in the bonsaigarden.
Details see pull request.

### PR DESCRIPTION
**Pull request by Cl0ckm4n**
close #55 
restructure and extend Bonsai class
reallocate methods in HTTPCommunications.py ans Bonsai.py

automate the process for:
- cutting all branches
- replacing bonsais (Zypresse) when reaching level 2

This degree of automation is sufficient for my needs. Please give feedback and add suggestions for further features.

The portallogin is included also. Sorry for that. I need to get familiar with Github first ^^

@MasterZydra  Please check you emails regarding the previous PR (i used the email provided on your website). Thanks.

### CODE REVIEW

**Comment by MasterZydra** [comment]
@Cl0ckm4n regarding the mail: I already did what you asked for

**Comment by Cl0ckm4n** [comment]
> @Cl0ckm4n regarding the mail: I already did what you asked for

Ok thanks. Then it didn't work as i thought it would... Do you know any method to remove the commit or the PR from the history?

**Comment by MasterZydra** [comment]
@Cl0ckm4n have you removed the commit from your fork?

I could try to delete the whole PR.

**Comment by Cl0ckm4n** [comment]
Yeah i think i deleted it with the git-rebase command.
That would be very kind of you. :D

I apologize for the circumstances

**Comment by MasterZydra** [comment]
@Cl0ckm4n I cannot delete the PR. This is only possible by the support team. And they only do it if the data is really sensitive.

Maybe you could try this https://stackoverflow.com/a/70602570/10618907.

**Comment by Cl0ckm4n** [comment]
Ok thanks, i think that did the trick.

Now this PR can be merged eventually.

**Pull request merged**
