### PR TITLE
add honey functionalities

### PR DESCRIPTION
**Pull request by Cl0ckm4n**

### CODE REVIEW

**Comment by MasterZydra** [comment]
Thanks @Cl0ckm4n. I try to take a look this week at your Pats

**Comment by Cl0ckm4n** [comment]
Thanks :)
I hope you have the honey feature already?

I had a little trouble with my fork repository... ^^
Is it best practice to mirror the master and only adapt the actions part and add new features via branches?

**Comment by MasterZydra** [comment]
Do you mean 1fcae4233aa5b034f91c042f8b06a7c25c569761?

If you have multiple feature additions it makes sense to fork the master and create a branch for each feature, yes.

**Comment by MasterZydra** [comment]
Hi @Cl0ckm4n,

after a long time, I am done merging your changes with the existing code.

While testing I noticed that the "send bees" function did not work for me.
The reason was the usage of the "send all bees" feature that only premium users have.
I added a switch that uses that AJAX call if it is a premium user, otherwise the bot iterates over all available hives.

**Comment by Cl0ckm4n** [comment]
Thanks for reviewing :D

I didn't think of that, good you tested it ^^

Maybe i have to create another account for testing ;)

**Pull request closed without merging**
